/* QUESTION ARCHIVE — ADMIN */
const {createClient}=window.supabase;const db=createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
const A={questions:[],chapters:[],categories:[],settings:{},user:null,profile:null};
document.addEventListener("DOMContentLoaded",async()=>{createBubbles();bindAdminUI();await bootAdmin()});
function createBubbles(){const box=document.getElementById("adminBubbles");for(let i=0;i<16;i++){const b=document.createElement("span"),s=20+Math.random()*90;b.style.width=b.style.height=`${s}px`;b.style.left=`${Math.random()*100}%`;b.style.animationDuration=`${20+Math.random()*25}s`;b.style.animationDelay=`${-Math.random()*25}s`;box.appendChild(b)}}
function bindAdminUI(){document.getElementById("loginForm").addEventListener("submit",login);document.getElementById("logoutBtn").addEventListener("click",logout);document.getElementById("accountLogout").addEventListener("click",logout);document.getElementById("addQuestionBtn").addEventListener("click",()=>openQuestionModal());document.getElementById("addChapterBtn").addEventListener("click",()=>openChapterModal());document.getElementById("addCategoryBtn").addEventListener("click",()=>openCategoryModal());document.getElementById("settingsForm").addEventListener("submit",saveSettings);document.getElementById("adminQuestionSearch").addEventListener("input",renderQuestionsTable);document.querySelectorAll(".side-link").forEach(b=>b.addEventListener("click",()=>switchSection(b.dataset.section)));document.querySelectorAll("[data-close]").forEach(x=>x.addEventListener("click",closeModal));document.getElementById("sidebarToggle").addEventListener("click",()=>document.querySelector(".sidebar").classList.toggle("open"));const adminToggle=document.getElementById("adminLanguageToggle");adminToggle.addEventListener("click",()=>QA_I18N.setLanguage(QA_I18N.get()==="ar"?"en":"ar"))}
async function bootAdmin(){showLogin(true);const{data:{session}}=await db.auth.getSession();if(session){const ok=await loadIdentity(session.user);if(ok)await loadAdminData()}}
async function login(e){e.preventDefault();const btn=document.getElementById("loginBtn"),msg=document.getElementById("loginMessage");btn.disabled=true;btn.textContent="جاري تسجيل الدخول...";msg.textContent="";try{const email=document.getElementById("loginEmail").value.trim(),password=document.getElementById("loginPassword").value;const{data,error}=await db.auth.signInWithPassword({email,password});if(error)throw error;if(!await loadIdentity(data.user)){await db.auth.signOut();throw new Error("ACCESS_DENIED")}await loadAdminData()}catch(err){console.error(err);msg.textContent=err.message==="ACCESS_DENIED"?"الدخول مرفوض. الحساب لازم يكون أدمن.":"البريد الإلكتروني أو كلمة المرور غير صحيحة."}finally{btn.disabled=false;btn.textContent="دخول"}}
async function loadIdentity(user){const{data,error}=await db.from("profiles").select("id,display_name,role").eq("id",user.id).single();if(error||!data||data.role!=="admin"){document.getElementById("loginMessage").textContent="الدخول مرفوض. الحساب لازم يكون أدمن.";return false}A.user=user;A.profile=data;document.getElementById("adminIdentity").textContent=data.display_name||user.email;document.getElementById("accountEmail").textContent=user.email;document.getElementById("accountRole").textContent=`الدور: ${data.role==="admin"?"أدمن":"طالب"}`;return true}
async function loadAdminData(){try{const[q,ch,cat,settings]=await Promise.all([db.from("questions").select("*").order("created_at",{ascending:false}),db.from("chapters").select("*").order("display_order",{ascending:true}),db.from("categories").select("*").order("name",{ascending:true}),db.from("site_settings").select("key,value")]);for(const r of[q,ch,cat,settings])if(r.error)throw r.error;A.questions=q.data||[];A.chapters=ch.data||[];A.categories=cat.data||[];A.settings=Object.fromEntries((settings.data||[]).map(x=>[x.key,x.value]));showLogin(false);renderAll()}catch(err){console.error(err);showLogin(true);document.getElementById("loginMessage").textContent="تعذر تحميل بيانات لوحة التحكم. راجع RLS ودور الحساب."}}
function renderAll(){document.getElementById("mQuestions").textContent=A.questions.length;document.getElementById("mPublished").textContent=A.questions.filter(q=>q.published).length;document.getElementById("mChapters").textContent=A.chapters.length;document.getElementById("mCategories").textContent=A.categories.length;renderRecent();renderQuestionsTable();renderChapters();renderCategories();renderSettings()}
function switchSection(name){document.querySelectorAll(".side-link").forEach(x=>x.classList.toggle("active",x.dataset.section===name));document.querySelectorAll(".panel-section").forEach(x=>x.classList.toggle("active",x.id===`section-${name}`));const active=document.querySelector(`.side-link[data-section="${name}"]`);document.getElementById("sectionTitle").textContent=active?active.textContent.trim():name;document.querySelector(".sidebar").classList.remove("open")}
function renderRecent(){const r=A.questions.slice(0,7);document.getElementById("recentQuestions").innerHTML=r.length?r.map(q=>`<div class="recent-item"><span>${esc(q.title)}</span><small>${q.published?"منشور":"مسودة"}</small></div>`).join(""):`<div class="state-message">لا توجد أسئلة</div>`}
function renderQuestionsTable(){const term=document.getElementById("adminQuestionSearch").value.trim().toLowerCase();const list=A.questions.filter(q=>!term||[q.title,q.question_text].join(" ").toLowerCase().includes(term));document.getElementById("questionsTable").innerHTML=list.map(q=>{const c=A.chapters.find(x=>x.id===q.chapter_id),cat=A.categories.find(x=>x.id===q.category_id);return`<tr><td>${q.id}</td><td>${esc(q.title)}</td><td>${esc(c?.title||"—")}</td><td>${esc(cat?.name||"—")}</td><td><span class="badge ${q.published?"on":"off"}">${q.published?"منشور":"مسودة"}</span></td><td>${formatDate(q.created_at)}</td><td><div class="row-actions"><button class="icon-btn" onclick="editQuestion('${attr(q.id)}')">تعديل</button><button class="icon-btn danger" onclick="deleteQuestion('${attr(q.id)}')">حذف</button></div></td></tr>`}).join("")||`<tr><td colspan="7">لا توجد أسئلة</td></tr>`}
function renderChapters(){document.getElementById("chaptersAdmin").innerHTML=A.chapters.map((c,i)=>`<div class="list-row"><span class="order">#${c.display_order??i+1}</span><strong>${esc(c.title)}</strong><span>${esc(c.description||"")}</span><span class="row-actions"><button class="icon-btn" onclick="editChapter('${attr(c.id)}')">تعديل</button><button class="icon-btn danger" onclick="deleteChapter('${attr(c.id)}')">حذف</button></span></div>`).join("")||`<div class="state-message">لا توجد فصول</div>`}
function renderCategories(){document.getElementById("categoriesAdmin").innerHTML=A.categories.map(c=>`<div class="list-row"><span class="order">CAT</span><strong>${esc(c.name)}</strong><span>${esc(c.slug||"")} · ${esc(c.description||"")}</span><span class="row-actions"><button class="icon-btn" onclick="editCategory('${attr(c.id)}')">تعديل</button><button class="icon-btn danger" onclick="deleteCategory('${attr(c.id)}')">حذف</button></span></div>`).join("")||`<div class="state-message">لا توجد تصنيفات</div>`}
function renderSettings(){document.getElementById("sSiteName").value=A.settings.site_name||"QUESTION ARCHIVE";document.getElementById("sDescription").value=A.settings.site_description||"";document.getElementById("sWhatsApp").value=A.settings.whatsapp_number||"";document.getElementById("sWhatsAppMessage").value=A.settings.whatsapp_message||"";document.getElementById("sEmail").value=A.settings.contact_email||"";document.getElementById("sFooter").value=A.settings.footer_text||"© 2026 Question Archive"}
function openQuestionModal(q=null){const chapters=A.chapters.map(c=>`<option value="${attr(c.id)}" ${q?.chapter_id===c.id?"selected":""}>${esc(c.title)}</option>`).join(""),cats=A.categories.map(c=>`<option value="${attr(c.id)}" ${q?.category_id===c.id?"selected":""}>${esc(c.name)}</option>`).join("");openModal(`<p class="eyebrow">${q?"تعديل السؤال":"ملف سؤال جديد"}</p><h3>${q?"تعديل السؤال":"إضافة سؤال وشرح"}</h3><form id="questionForm" class="modal-form"><label class="full">عنوان السؤال<input id="qTitle" required value="${attr(q?.title)}"></label><label class="full">السؤال<textarea id="qText" rows="5" required>${esc(q?.question_text)}</textarea></label><label>الإجابة<textarea id="qAnswer" rows="5">${esc(q?.answer)}</textarea></label><label>الشرح<textarea id="qExplanation" rows="5">${esc(q?.explanation)}</textarea></label><label>الفصل<select id="qChapter"><option value="">بدون فصل</option>${chapters}</select></label><label>التصنيف<select id="qCategory"><option value="">بدون تصنيف</option>${cats}</select></label><label>رابط الصورة<input id="qImage" value="${attr(q?.image_url)}" placeholder="https://..."></label><label>رابط الفيديو<input id="qVideo" value="${attr(q?.video_url)}" placeholder="YouTube / MP4"></label><label class="full">كود اختياري<textarea id="qCode" rows="6">${esc(q?.code)}</textarea></label><label class="check-row full"><input id="qPublished" type="checkbox" ${q?.published?"checked":""}> نشر السؤال للطلاب</label><button class="primary" type="submit">${q?"تحديث السؤال":"حفظ ونشر/حفظ كمسودة"}</button><div id="modalMessage" class="form-message"></div></form>`);document.getElementById("questionForm").addEventListener("submit",e=>saveQuestion(e,q?.id))}
async function saveQuestion(e,id){e.preventDefault();const btn=e.target.querySelector("button[type=submit]");btn.disabled=true;btn.textContent="جاري الحفظ...";const payload={title:document.getElementById("qTitle").value.trim(),question_text:document.getElementById("qText").value.trim(),answer:document.getElementById("qAnswer").value.trim()||null,explanation:document.getElementById("qExplanation").value.trim()||null,chapter_id:document.getElementById("qChapter").value||null,category_id:document.getElementById("qCategory").value||null,image_url:document.getElementById("qImage").value.trim()||null,video_url:document.getElementById("qVideo").value.trim()||null,code:document.getElementById("qCode").value.trim()||null,published:document.getElementById("qPublished").checked};try{const r=id?await db.from("questions").update(payload).eq("id",id):await db.from("questions").insert(payload);if(r.error)throw r.error;closeModal();await loadAdminData();toast(id?"تم تعديل السؤال":"تم حفظ السؤال بنجاح")}catch(err){console.error(err);document.getElementById("modalMessage").textContent="تعذر حفظ السؤال. راجع البيانات وRLS.";btn.disabled=false;btn.textContent=id?"تحديث السؤال":"حفظ السؤال"}}
window.editQuestion=id=>{const q=A.questions.find(x=>String(x.id)===String(id));if(q)openQuestionModal(q)};window.deleteQuestion=async id=>{if(!confirm("متأكد إنك عايز تحذف السؤال؟"))return;try{const{error}=await db.from("questions").delete().eq("id",id);if(error)throw error;await loadAdminData();toast("تم حذف السؤال")}catch(e){console.error(e);toast("تعذر حذف السؤال")}};
function openChapterModal(c=null){openModal(`<p class="eyebrow">${c?"تعديل فصل":"فصل جديد"}</p><h3>${c?"تعديل الفصل":"إضافة فصل"}</h3><form id="chapterForm" class="modal-form"><label class="full">اسم الفصل<input id="cTitle" required value="${attr(c?.title)}"></label><label class="full">وصف الفصل<textarea id="cDescription" rows="4">${esc(c?.description)}</textarea></label><label>ترتيب الظهور<input id="cOrder" type="number" min="0" value="${c?.display_order??A.chapters.length+1}"></label><button class="primary" type="submit">${c?"تحديث الفصل":"حفظ الفصل"}</button><div id="modalMessage" class="form-message"></div></form>`);document.getElementById("chapterForm").addEventListener("submit",e=>saveChapter(e,c?.id))}
async function saveChapter(e,id){e.preventDefault();const b=e.target.querySelector("button");b.disabled=true;const p={title:document.getElementById("cTitle").value.trim(),description:document.getElementById("cDescription").value.trim()||null,display_order:Number(document.getElementById("cOrder").value)||0};try{const r=id?await db.from("chapters").update(p).eq("id",id):await db.from("chapters").insert(p);if(r.error)throw r.error;closeModal();await loadAdminData();toast("تم حفظ الفصل")}catch(err){document.getElementById("modalMessage").textContent="تعذر حفظ الفصل";b.disabled=false}}
window.editChapter=id=>{const c=A.chapters.find(x=>String(x.id)===String(id));if(c)openChapterModal(c)};window.deleteChapter=async id=>{if(!confirm("متأكد من حذف الفصل؟"))return;try{const{error}=await db.from("chapters").delete().eq("id",id);if(error)throw error;await loadAdminData();toast("تم حذف الفصل")}catch(e){toast("تعذر حذف الفصل. قد تكون هناك أسئلة مرتبطة به.")}};
function openCategoryModal(c=null){openModal(`<p class="eyebrow">${c?"تعديل تصنيف":"تصنيف جديد"}</p><h3>${c?"تعديل التصنيف":"إضافة تصنيف"}</h3><form id="categoryForm" class="modal-form"><label>اسم التصنيف<input id="catName" required value="${attr(c?.name)}"></label><label>Slug<input id="catSlug" required value="${attr(c?.slug)}"></label><label class="full">وصف<textarea id="catDescription" rows="4">${esc(c?.description)}</textarea></label><button class="primary" type="submit">${c?"تحديث التصنيف":"حفظ التصنيف"}</button><div id="modalMessage" class="form-message"></div></form>`);document.getElementById("categoryForm").addEventListener("submit",e=>saveCategory(e,c?.id))}
async function saveCategory(e,id){e.preventDefault();const b=e.target.querySelector("button");b.disabled=true;const p={name:document.getElementById("catName").value.trim(),slug:document.getElementById("catSlug").value.trim().toLowerCase().replace(/\s+/g,"-"),description:document.getElementById("catDescription").value.trim()||null};try{const r=id?await db.from("categories").update(p).eq("id",id):await db.from("categories").insert(p);if(r.error)throw r.error;closeModal();await loadAdminData();toast("تم حفظ التصنيف")}catch(err){document.getElementById("modalMessage").textContent="تعذر حفظ التصنيف";b.disabled=false}}
window.editCategory=id=>{const c=A.categories.find(x=>String(x.id)===String(id));if(c)openCategoryModal(c)};window.deleteCategory=async id=>{if(!confirm("متأكد من حذف التصنيف؟"))return;try{const{error}=await db.from("categories").delete().eq("id",id);if(error)throw error;await loadAdminData();toast("تم حذف التصنيف")}catch(e){toast("تعذر حذف التصنيف")}};
async function saveSettings(e){e.preventDefault();const b=e.target.querySelector("button[type=submit]");b.disabled=true;const values={site_name:document.getElementById("sSiteName").value.trim(),site_description:document.getElementById("sDescription").value.trim(),whatsapp_number:document.getElementById("sWhatsApp").value.trim(),whatsapp_message:document.getElementById("sWhatsAppMessage").value.trim(),contact_email:document.getElementById("sEmail").value.trim(),footer_text:document.getElementById("sFooter").value.trim()};try{for(const[key,value]of Object.entries(values)){const{error}=await db.from("site_settings").upsert({key,value},{onConflict:"key"});if(error)throw error}A.settings={...A.settings,...values};document.getElementById("settingsMessage").textContent="تم حفظ الإعدادات بنجاح";toast("تم حفظ الإعدادات")}catch(err){console.error(err);document.getElementById("settingsMessage").textContent="حصلت مشكلة في الحفظ"}finally{b.disabled=false}}
async function logout(){await db.auth.signOut();A.user=null;A.profile=null;showLogin(true);document.getElementById("loginMessage").textContent="تم تسجيل الخروج"}
function showLogin(show){document.getElementById("loginView").classList.toggle("hidden",!show);document.getElementById("adminApp").classList.toggle("hidden",show)}
function openModal(html){document.getElementById("modalContent").innerHTML=html;document.getElementById("modal").classList.remove("hidden")}
function closeModal(){document.getElementById("modal").classList.add("hidden");document.getElementById("modalContent").innerHTML=""}
function toast(m){const r=document.getElementById("toastRegion"),e=document.createElement("div");e.className="toast";e.textContent=m;r.appendChild(e);setTimeout(()=>e.remove(),2800)}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function attr(v){return esc(v).replace(/\n/g,"&#10;")}function formatDate(v){try{return new Date(v).toLocaleDateString(QA_I18N.get()==="ar"?"ar-EG":"en-GB")}catch{return"—"}}
window.addEventListener("qa-language-change",()=>{document.querySelectorAll(".language-toggle").forEach(b=>{b.textContent=QA_I18N.get()==="ar"?"EN":"عربي"});const active=document.querySelector(".side-link.active");if(active)document.getElementById("sectionTitle").textContent=active.textContent.trim();renderAll()});
