-- =========================================================
-- QUESTION ARCHIVE — SUPABASE SCHEMA
-- Run this entire file in Supabase SQL Editor.
-- No admin password is stored here.
-- =========================================================

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role text not null default 'student' check (role in ('student','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.chapters (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  display_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  title text not null,
  question_text text not null,
  answer text,
  explanation text,
  chapter_id uuid references public.chapters(id) on delete set null,
  category_id uuid references public.categories(id) on delete set null,
  image_url text,
  video_url text,
  code text,
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  key text primary key,
  value text,
  is_public boolean not null default true,
  updated_at timestamptz not null default now()
);

create index if not exists questions_published_idx on public.questions(published);
create index if not exists questions_chapter_idx on public.questions(chapter_id);
create index if not exists questions_category_idx on public.questions(category_id);
create index if not exists chapters_order_idx on public.chapters(display_order);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists questions_set_updated_at on public.questions;
create trigger questions_set_updated_at
before update on public.questions
for each row execute function public.set_updated_at();

create or replace function public.set_settings_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists site_settings_set_updated_at on public.site_settings;
create trigger site_settings_set_updated_at
before update on public.site_settings
for each row execute function public.set_settings_updated_at();

-- Security-definer helper avoids recursive RLS checks on profiles.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

alter table public.profiles enable row level security;
alter table public.chapters enable row level security;
alter table public.categories enable row level security;
alter table public.questions enable row level security;
alter table public.site_settings enable row level security;

-- Remove policies if this schema is re-run.
drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "chapters_public_select" on public.chapters;
drop policy if exists "chapters_admin_insert" on public.chapters;
drop policy if exists "chapters_admin_update" on public.chapters;
drop policy if exists "chapters_admin_delete" on public.chapters;

drop policy if exists "categories_public_select" on public.categories;
drop policy if exists "categories_admin_insert" on public.categories;
drop policy if exists "categories_admin_update" on public.categories;
drop policy if exists "categories_admin_delete" on public.categories;

drop policy if exists "questions_public_published_select" on public.questions;
drop policy if exists "questions_admin_select" on public.questions;
drop policy if exists "questions_admin_insert" on public.questions;
drop policy if exists "questions_admin_update" on public.questions;
drop policy if exists "questions_admin_delete" on public.questions;

drop policy if exists "settings_public_select" on public.site_settings;
drop policy if exists "settings_admin_select" on public.site_settings;
drop policy if exists "settings_admin_insert" on public.site_settings;
drop policy if exists "settings_admin_update" on public.site_settings;
drop policy if exists "settings_admin_delete" on public.site_settings;

-- Profiles: a user may read only their own profile.
-- There is intentionally NO public INSERT policy, preventing self-promotion to admin.
create policy "profiles_select_own"
on public.profiles for select to authenticated
using (id = auth.uid());

-- Public chapters/categories are readable. Writes are admin-only.
create policy "chapters_public_select"
on public.chapters for select to anon, authenticated
using (true);

create policy "chapters_admin_insert"
on public.chapters for insert to authenticated
with check (public.is_admin());

create policy "chapters_admin_update"
on public.chapters for update to authenticated
using (public.is_admin()) with check (public.is_admin());

create policy "chapters_admin_delete"
on public.chapters for delete to authenticated
using (public.is_admin());

create policy "categories_public_select"
on public.categories for select to anon, authenticated
using (true);

create policy "categories_admin_insert"
on public.categories for insert to authenticated
with check (public.is_admin());

create policy "categories_admin_update"
on public.categories for update to authenticated
using (public.is_admin()) with check (public.is_admin());

create policy "categories_admin_delete"
on public.categories for delete to authenticated
using (public.is_admin());

-- Questions: public sees only published records.
create policy "questions_public_published_select"
on public.questions for select to anon, authenticated
using (published = true);

-- Admin sees and manages all questions.
create policy "questions_admin_select"
on public.questions for select to authenticated
using (public.is_admin());

create policy "questions_admin_insert"
on public.questions for insert to authenticated
with check (public.is_admin());

create policy "questions_admin_update"
on public.questions for update to authenticated
using (public.is_admin()) with check (public.is_admin());

create policy "questions_admin_delete"
on public.questions for delete to authenticated
using (public.is_admin());

-- Public settings only when explicitly marked public.
create policy "settings_public_select"
on public.site_settings for select to anon, authenticated
using (is_public = true);

create policy "settings_admin_select"
on public.site_settings for select to authenticated
using (public.is_admin());

create policy "settings_admin_insert"
on public.site_settings for insert to authenticated
with check (public.is_admin());

create policy "settings_admin_update"
on public.site_settings for update to authenticated
using (public.is_admin()) with check (public.is_admin());

create policy "settings_admin_delete"
on public.site_settings for delete to authenticated
using (public.is_admin());

-- Seed/demo data. Safe to delete after setup.
insert into public.chapters (title, description, display_order)
values
  ('Chapter 1', 'Introduction', 1),
  ('Chapter 2', 'Review Files', 2),
  ('Chapter 3', 'Practice', 3)
on conflict do nothing;

insert into public.categories (name, slug, description)
values
  ('Grammar', 'grammar', 'Grammar questions'),
  ('Vocabulary', 'vocabulary', 'Vocabulary questions'),
  ('Reading', 'reading', 'Reading and comprehension')
on conflict (name) do nothing;

insert into public.site_settings (key, value, is_public)
values
  ('site_name', 'QUESTION ARCHIVE', true),
  ('site_description', 'Your personal archive of questions, answers and explanations.', true),
  ('whatsapp_number', '', true),
  ('whatsapp_message', 'Hello, I found a problem with a question.', true),
  ('contact_email', '', true),
  ('footer_text', '© 2026 Question Archive', true)
on conflict (key) do nothing;

-- Demo questions are published so the public page is immediately testable.
insert into public.questions (title, question_text, answer, explanation, published)
select
  'Chapter 1 — Question 01',
  'Demo question: replace this with your own educational question.',
  'Demo answer',
  'Demo explanation. This record exists only to verify the public archive flow.',
  true
where not exists (select 1 from public.questions);

-- IMPORTANT:
-- Create your admin in Supabase Dashboard > Authentication > Users.
-- Then run only this statement after replacing the UUID:
--
-- insert into public.profiles (id, display_name, role)
-- values ('YOUR-AUTH-USER-UUID', 'Administrator', 'admin');
--
-- Never store the admin password in this SQL file.

-- Optional media storage bucket for future/admin uploads.
insert into storage.buckets (id, name, public)
values ('question-media', 'question-media', true)
on conflict (id) do nothing;

drop policy if exists "question_media_public_read" on storage.objects;
drop policy if exists "question_media_admin_insert" on storage.objects;
drop policy if exists "question_media_admin_update" on storage.objects;
drop policy if exists "question_media_admin_delete" on storage.objects;

create policy "question_media_public_read"
on storage.objects for select to anon, authenticated
using (bucket_id = 'question-media');

create policy "question_media_admin_insert"
on storage.objects for insert to authenticated
with check (bucket_id = 'question-media' and public.is_admin());

create policy "question_media_admin_update"
on storage.objects for update to authenticated
using (bucket_id = 'question-media' and public.is_admin())
with check (bucket_id = 'question-media' and public.is_admin());

create policy "question_media_admin_delete"
on storage.objects for delete to authenticated
using (bucket_id = 'question-media' and public.is_admin());
